services:
  familiar:
    container_name: familiar-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FAMILIAR_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: familiar-postgres
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-familiar}
      POSTGRES_DB: ${POSTGRES_DB:-familiar}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./config/init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
    driver: local